---
- name: Upload updating script
  copy:
    src: update_schedules.sh
    dest: /opt/src/update_schedules.sh
    mode: 0755
  register: updater_changed

- name: Initialize log file
  become: yes
  file:
    path: /var/log/sotm_schedules.log
    state: touch
    owner: zverik
    mode: 0644
    access_time: preserve
    modification_time: preserve

- name: Create schedules data directory
  file:
    path: /opt/src/schedule-convert/data
    state: directory

- name: Upload data files for the schedules
  copy:
    src: "{{ item }}"
    dest: /opt/src/schedule-convert/data
  with_fileglob:
    - "*.ini"
  register: files_updated

- name: Set up crontab for the updated
  cron:
    name: sotm_schedules
    minute: "5"
    hour: "*"
    job: /opt/src/update_schedules.sh 2> /var/log/sotm_schedules.log

- name: Update schedules
  when: git_updated.changed or updater_changed.changed or files_updated.changed
  command: /opt/src/update_schedules.sh
