- name: Create directory for ommm
  file:
    path: "{{ sites }}/osmz.ru/ommm"
    state: directory

- name: Upload files for ommm
  copy:
    src: "{{ item }}"
    dest: "{{ sites }}/osmz.ru/ommm"
  with_fileglob: "ommm/*"
  tags: [ ommm, update ]

- name: Unpack tiles
  unarchive:
    src: ommm-tiles.tar
    dest: "{{ sites }}/osmz.ru/ommm"
    creates: "{{ sites }}/osmz.ru/ommm/ommm-tiles"

- name: Create directory for presentations (not included)
  file:
    path: "{{ sites }}/osmz.ru/ommm/pres"
    state: directory

- name: Add presentations to backup
  become: true
  cron:
    name: backup ommm
    minute: 0
    hour: 4
    job: /root/make_backup OMMM "{{ sites }}/osmz.ru/ommm/pres"

- name: Restore presentations from backup
  when: "'restore' in ansible_run_tags"
  become: yes
  command:
    argv:
      - "/root/extract_backup"
      - OMMM
      - '*'
    chdir: /

- name: Create apache log directory
  become: yes
  file:
    path: "/var/log/apache2/{{ domain }}"
    state: directory
    mode: 0755
    owner: www-data

- name: Check that the certificate exists
  become: yes
  stat:
    path: "{{ cert_path.ommm }}/privkey.pem"
  register: ommm_cert

- name: Add apache domain
  become: yes
  template:
    src: domain.j2
    dest: /etc/apache2/sites-available/{{ domain }}.conf
  notify: reload apache

- name: Enable apache domain
  become: yes
  file:
    src: /etc/apache2/sites-available/{{ domain }}.conf
    dest: /etc/apache2/sites-enabled/{{ domain }}.conf
    state: link
  notify: reload apache
