---
- name: Install subversion packages
  apt:
    name:
      - subversion
      - sasl2-bin
    state: present

- name: Create svn system user
  user:
    name: svn
    create_home: false
    password: '!'

- name: Create svn directory
  file:
    path: /var/svn
    state: directory
    owner: svn
    group: svn

- name: Check that we have files inside the svn directory
  stat:
    path: /var/svn/svnrepo/conf
  register: svn_dir

- name: Initialize the SVN repo
  when: not svn_dir.stat.exists
  command: svnadmin create /var/svn/svnrepo
  become: true
  become_user: svn

- name: Upload the configuration
  copy:
    src: svnserve.conf
    dest: /var/svn/svnrepo/conf/

- name: Create the SVN user
  shell: echo "{{ svn_password }}" | saslpasswd2 -p -c -f /var/svn/svnrepo/conf/sasldb -u {{ svn_realm }} {{ svn_user }}
  args:
    creates: /var/svn/svnrepo/conf/sasldb

- name: Upload the systemd config
  copy:
    src: svnserve.service
    dest: /etc/systemd/system/

- name: Open the svn 3690 port
  ufw:
    port: 3690
    proto: tcp
    rule: allow
  notify: restart ufw

- name: Enable svnserve daemon
  systemd:
    name: svnserve
    enabled: true
    state: started
    daemon_reload: true

- name: Add the svn directory to backup
  lineinfile:
    path: /etc/cron.daily/backup
    line: /root/make_backup Svn /var/svn/svnrepo
    regexp: 'make.* Svn '
    state: present
  tags: backup

- name: Restore SVN
  when: "'restore' in ansible_run_tags"
  command:
    argv:
      - "/root/extract_backup"
      - Svn
      - '*'
    chdir: /
