#!/bin/bash
set -u -e
[ "$(whoami)" != "root" ] && echo "Please run this script as a root" && exit 1
[ $# -lt 2 ] && echo "Usage: $0 <prefix> <db> [<path> ...]" && exit 1

source /root/borg_env
PREFIX="$1"
shift

DBNAME="$1"
DUMP="/tmp/$DBNAME.sql"
shift

/usr/bin/mariadb-dump "$DBNAME" > "$DUMP" 2>/var/log/backup_db_errors.log

$BORG create --compression zstd,5 ::"${PREFIX}_{now:%Y-%m-%d_%H%M}" "$DUMP" $@

$BORG prune --glob-archives "${PREFIX}_*" --keep-daily=7 --keep-weekly=2 --keep-monthly=3

rm "$DUMP"
