certbot_admin_email: ilya@zverev.info
certbot_create_if_missing: true
certbot_create_method: standalone
certbot_create_standalone_stop_services: [apache2]

cert_path:
  josm: /etc/letsencrypt/live/josm.ru
  izverev: /etc/letsencrypt/live/josm.ru
  sotm: /etc/letsencrypt/live/josm.ru
  textual: /etc/letsencrypt/live/textual.ru
  not: /etc/letsencrypt/live/textual.ru
  pinx: /etc/letsencrypt/live/textual.ru
  pma: /etc/letsencrypt/live/textual.ru
  offsets: /etc/letsencrypt/live/textual.ru
  awstats: /etc/letsencrypt/live/textual.ru
  seeing: /etc/letsencrypt/live/seen.textual.ru
  osmz: /etc/letsencrypt/live/osmz.ru
  ommm: /etc/letsencrypt/live/osmz.ru
  level0: /etc/letsencrypt/live/osmz.ru
  revert: /etc/letsencrypt/live/osmz.ru
  whosthat: /etc/letsencrypt/live/osmz.ru
  radio: /etc/letsencrypt/live/osmz.ru
  auth: /etc/letsencrypt/live/osmz.ru
  bigmap: /etc/letsencrypt/live/osmz.ru
  audit: /etc/letsencrypt/live/osmz.ru
  awards: /etc/letsencrypt/live/osmz.ru
  schedules: /etc/letsencrypt/live/osmz.ru
  streak: /etc/letsencrypt/live/osmz.ru
  shtosm: /etc/letsencrypt/live/shtosm.ru
  tw_shtosm: /etc/letsencrypt/live/shtosm.ru
  nelgi: /etc/letsencrypt/live/nelgi31.ee
  izvee: /etc/letsencrypt/live/izv.ee

certbot_certs:
  - email: ilya@zverev.info
    domains:
      - josm.ru
      - zverev.info
      - ilya.zverev.info
      - sotm-baltics.org
      - 2013.sotm-baltics.org
  - email: ilya@zverev.info
    domains:
      - textual.ru
      - not.textual.ru
      - pin-x.textual.ru
      - phpmyadmin.textual.ru
      - offsets.textual.ru
      - awstats.textual.ru
  - email: ilya@zverev.info
    domains:
      - seen.textual.ru
  - email: ilya@zverev.info
    domains:
      - osmz.ru
      - level0.osmz.ru
      - revert.osmz.ru
      - radio.osmz.ru
      - auth.osmz.ru
      - whosthat.osmz.ru
      - ommm.osmz.ru
      - bigmap.osmz.ru
      - audit.osmz.ru
      - awards.osmz.ru
      - sotm.osmz.ru
      - streak.osmz.ru
  - email: ilya@zverev.info
    domains:
      - nelgi31.ee
  - email: ilya@zverev.info
    domains:
      - shtosm.ru
      - twitter.shtosm.ru
  - domains:
      - izv.ee
      - t.izv.ee

# Needed to add --expand
certbot_create_command: >-
  {{ certbot_script }} certonly --{{ certbot_create_method  }}
  {{ '--hsts' if certbot_hsts else '' }}
  {{ '--test-cert' if certbot_testmode else '' }}
  --noninteractive --agree-tos
  --expand
  --email {{ cert_item.email | default(certbot_admin_email) }}
  {{ '--webroot-path ' if certbot_create_method == 'webroot'  else '' }}
  {{ cert_item.webroot | default(certbot_webroot) if certbot_create_method == 'webroot' else '' }}
  -d {{ cert_item.domains | join(',') }}
  {{ '--pre-hook /etc/letsencrypt/renewal-hooks/pre/stop_services'
    if certbot_create_standalone_stop_services and certbot_create_method == 'standalone'
  else '' }}
  {{ '--post-hook /etc/letsencrypt/renewal-hooks/post/start_services'
    if certbot_create_standalone_stop_services and certbot_create_method == 'standalone'
  else '' }}

