---
- name: Add backing up home to crontab
  cron:
    name: backup home
    minute: 0
    hour: 4
    job: /root/make_backup TextualHome /home

- name: Restore home
  when: "'restore' in ansible_run_tags"
  command:
    argv:
      - "/root/extract_backup"
      - TextualHome
      - '*'
    chdir: /
