---
- name: Add backing up home to crontab
  lineinfile:
    path: /etc/cron.daily/backup
    line: /root/make_backup TextualHome /home
    regexp: 'make.* TextualHome '
    state: present

- name: Restore home
  when: "'restore' in ansible_run_tags"
  command:
    argv:
      - "/root/extract_backup"
      - TextualHome
      - '*'
    chdir: /
