---
- name: Create directory for not.textual.ru
  become: yes
  file:
    path: "{{ sites }}/not.textual.ru"
    state: directory
    owner: www-data

- name: Add not-textual to backup
  become: yes
  cron:
    name: backup not.textual
    minute: 0
    hour: 4
    job: /root/make_backup NotTextual "{{ sites }}/not.textual.ru"

- name: Restore not-textual
  when: "'restore' in ansible_run_tags"
  become: yes
  command:
    argv:
      - "/root/extract_backup"
      - NotTextual
      - '*'
    chdir: /

- name: Create apache log directory
  become: yes
  file:
    path: /var/log/apache2/not.textual.ru
    state: directory
    mode: 0755
    owner: www-data

- name: Check that the certificate exists
  become: yes
  stat:
    path: "{{ letsencrypt_cert_path }}/privkey.pem"
  register: not_textual_cert

- name: Add apache domain
  become: yes
  template:
    src: domain.j2
    dest: /etc/apache2/sites-available/not.textual.ru.conf
  notify: reload apache

- name: Enable apache domain
  become: yes
  file:
    src: /etc/apache2/sites-available/not.textual.ru.conf
    dest: /etc/apache2/sites-enabled/not.textual.ru.conf
    state: link
  notify: reload apache
