---
- name: Check out IODB
  git:
    repo: https://github.com/Zverik/iodb
    dest: "{{ sites }}/{{ domain }}"

- name: Run composer
  community.general.composer:
    command: install
    working_dir: "{{ sites }}/{{ domain }}"

- name: Upload config
  template:
    src: config.php
    dest: "{{ sites }}/{{ domain }}/www/config.php"

- name: Create iodb mysql database
  become: true
  mysql_db:
    name: "{{ offsets_mysql_db }}"
    state: present
  register: created_db

- name: Create iodb mysql user
  become: true
  mysql_user:
    name: "{{ offsets_mysql_user }}"
    password: "{{ offsets_mysql_password }}"
    priv: "{{ offsets_mysql_db }}.*:ALL"

- name: Initialize iodb tables
  when: created_db is changed
  command:
    argv:
      - /usr/bin/php
      - "{{ sites }}/{{ domain }}/www/iodb.php"
      - create

- name: Upload database dump script
  become: yes
  template:
    src: iodb_backup.sh
    dest: /etc/cron.daily/iodb_backup
    mode: '0755'

- name: Upload downloads pruning script
  become: yes
  template:
    src: prune_archive.sh
    dest: /etc/cron.monthly/iodb_prune
    mode: '0755'

- name: Add iodb to backup
  become: yes
  cron:
    name: backup iodb
    minute: 0
    hour: 4
    job: /root/make_backup_db Iodb {{ offsets_mysql_db }} "{{ sites }}/{{ domain }}/www/download"

- name: Restore iodb
  when: "'restore' in ansible_run_tags"
  become: yes
  command:
    argv:
      - "/root/extract_backup_db"
      - Iodb
      - "{{ offsets_mysql_db }}"
      - '*'
    chdir: /

- name: Create apache log directory
  become: yes
  file:
    path: "/var/log/apache2/{{ domain }}"
    state: directory
    mode: 0755
    owner: www-data

- name: Check that the certificate exists
  become: yes
  stat:
    path: "{{ cert_path.offsets }}/privkey.pem"
  register: offsets_cert

- name: Add apache domain
  become: yes
  template:
    src: offsets.textual.ru
    dest: /etc/apache2/sites-available/{{ domain }}.conf
  notify: reload apache

- name: Enable apache domain
  become: yes
  file:
    src: /etc/apache2/sites-available/{{ domain }}.conf
    dest: /etc/apache2/sites-enabled/{{ domain }}.conf
    state: link
  notify: reload apache
