---
- name: Install or update aegea
  import_tasks: aegea.yml
  vars:
    aegea_version: "{{ radio_aegea_version }}"
    path: "{{ sites }}/osmz.ru/radio"
    theme_name: radioosmru

- name: Create podcasts directory
  become: yes
  file:
    path: "{{ sites }}/osmz.ru/radio/podcast"
    state: directory
    owner: zverik

- name: Create radio mysql db
  become: true
  mysql_db:
    name: "{{ radio_mysql_db }}"
    state: present

- name: Create radio mysql user
  become: true
  mysql_user:
    name: "{{ radio_mysql_user }}"
    password: "{{ radio_mysql_password }}"
    priv: "{{ radio_mysql_db }}.*:ALL"

- name: Enable apache mod_rewrite
  become: yes
  apache2_module:
    name: rewrite
    state: present
  notify: restart apache

- name: Add radio to backup
  become: yes
  lineinfile:
    path: /etc/cron.daily/backup
    line: /root/make_backup_db Radio {{ radio_mysql_db }} "{{ sites }}/osmz.ru/radio/user" "{{ sites }}/osmz.ru/radio/pictures" "{{ sites }}/osmz.ru/radio/podcast"
    regexp: 'make.* Radio '
    state: present
  tags: backup

- name: Restore radio
  when: "'restore' in ansible_run_tags"
  become: yes
  command:
    argv:
      - "/root/extract_backup_db"
      - Radio
      - "{{ radio_mysql_db }}"
      - '*'
    chdir: /

- name: Create apache log directory
  become: yes
  file:
    path: "/var/log/apache2/{{ domain }}"
    state: directory
    mode: 0755
    owner: www-data

- name: Check that the certificate exists
  become: yes
  stat:
    path: "{{ cert_path.radio }}/privkey.pem"
  register: radio_cert

- name: Add apache domain
  become: yes
  template:
    src: domain.j2
    dest: /etc/apache2/sites-available/{{ domain }}.conf
  notify: reload apache

- name: Enable apache domain
  become: yes
  file:
    src: /etc/apache2/sites-available/{{ domain }}.conf
    dest: /etc/apache2/sites-enabled/{{ domain }}.conf
    state: link
  notify: reload apache
