---
- name: Install ZNC
  apt:
    name: znc
    state: present

- name: Add znc to backup
  cron:
    name: backup znc
    minute: 0
    hour: 4
    job: /root/make_backup Znc /var/lib/znc

- name: Restore znc
  when: "'restore' in ansible_run_tags"
  command:
    argv:
      - "/root/extract_backup"
      - Znc
      - '*'
    chdir: /

- name: Open firewall ports for ZNC
  ufw:
    port: 4999
    proto: tcp
    rule: allow
  notify: restart ufw

- name: Start and enable ZNC
  systemd:
    name: znc
    enabled: true
    state: started
