---
- name: Set up ppa for php7
  become: true
  apt_repository:
    repo: ppa:ondrej/php

- name: Install php7
  become: true
  apt:
    name:
      - php7.4
      - php7.4-fpm
      - php7.4-mysql
      - php7.4-gd
      - php7.4-mbstring
      - libapache2-mod-php7.4
      - libapache2-mod-fcgid
    state: present

- name: Install or update aegea
  import_tasks: aegea.yml
  vars:
    aegea_version: "{{ shtosm_aegea_version }}"
    path: "{{ sites }}/{{ domain }}"
    theme_name: shtosm

- name: Create seen mysql db
  become: true
  mysql_db:
    name: "{{ shtosm_mysql_db }}"
    state: present

- name: Create seen mysql user
  become: true
  mysql_user:
    name: "{{ shtosm_mysql_user }}"
    password: "{{ shtosm_mysql_password }}"
    priv: "{{ shtosm_mysql_db }}.*:ALL"

- name: Enable apache mod_rewrite and fcgi
  become: yes
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - fcgid
    - proxy_fcgi
  notify: restart apache

- name: Add shtosm to backup
  become: yes
  cron:
    name: backup shtosm
    minute: 0
    hour: 4
    job: /root/make_backup_db Shtosm {{ shtosm_mysql_db }} "{{ sites }}/{{ domain }}/user" "{{ sites }}/{{ domain }}/pictures"

- name: Restore shtosm
  when: "'restore' in ansible_run_tags"
  become: yes
  command:
    argv:
      - "/root/extract_backup_db"
      - Shtosm
      - "{{ shtosm_mysql_db }}"
      - '*'
    chdir: /

- name: Create apache log directory
  become: yes
  file:
    path: "/var/log/apache2/{{ domain }}"
    state: directory
    mode: 0755
    owner: www-data

- name: Check that the certificate exists
  become: yes
  stat:
    path: "{{ cert_path.shtosm }}/privkey.pem"
  register: shtosm_cert

- name: Add apache domain
  become: yes
  template:
    src: domain.j2
    dest: /etc/apache2/sites-available/{{ domain }}.conf
  notify: reload apache

- name: Enable apache domain
  become: yes
  file:
    src: /etc/apache2/sites-available/{{ domain }}.conf
    dest: /etc/apache2/sites-enabled/{{ domain }}.conf
    state: link
  notify: reload apache
